// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoFilterController from "./auto_filter_controller"
application.register("auto-filter", AutoFilterController)

import CaseAttachmentController from "./case_attachment_controller"
application.register("case-attachment", CaseAttachmentController)

import CaseFilesController from "./case_files_controller"
application.register("case-files", CaseFilesController)

import CaseFiltersController from "./case_filters_controller"
application.register("case-filters", CaseFiltersController)

import CaseQuickEditController from "./case_quick_edit_controller"
application.register("case-quick-edit", CaseQuickEditController)

import CaseStageController from "./case_stage_controller"
application.register("case-stage", CaseStageController)

import CaseSummaryController from "./case_summary_controller"
application.register("case-summary", CaseSummaryController)

import ChecklistTableController from "./checklist_table_controller"
application.register("checklist-table", ChecklistTableController)

import ChecklistTableFilterController from "./checklist_table_filter_controller"
application.register("checklist-table-filter", ChecklistTableFilterController)

import DraftEmailController from "./draft_email_controller"
application.register("draft-email", DraftEmailController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import EmailAttachmentController from "./email_attachment_controller"
application.register("email-attachment", EmailAttachmentController)

import EmailTemplateFiltersController from "./email_template_filters_controller"
application.register("email-template-filters", EmailTemplateFiltersController)

import EmailTemplatesEditController from "./email_templates_edit_controller"
application.register("email-templates-edit", EmailTemplatesEditController)

import EmailTemplatesSelectController from "./email_templates_select_controller"
application.register("email-templates-select", EmailTemplatesSelectController)

import EnergyBillUploadController from "./energy_bill_upload_controller"
application.register("energy-bill-upload", EnergyBillUploadController)

import ErrorSummaryController from "./error_summary_controller"
application.register("error-summary", ErrorSummaryController)

import ExpanderController from "./expander_controller"
application.register("expander", ExpanderController)

import FrameworkEditController from "./framework_edit_controller"
application.register("framework-edit", FrameworkEditController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RequestTypeController from "./request_type_controller"
application.register("request-type", RequestTypeController)

import SchoolPickerController from "./school_picker_controller"
application.register("school-picker", SchoolPickerController)

import SchoolPickerFiltersController from "./school_picker_filters_controller"
application.register("school-picker-filters", SchoolPickerFiltersController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import SelectOptionFilterController from "./select_option_filter_controller"
application.register("select-option-filter", SelectOptionFilterController)

import SelectOptionTextFieldController from "./select_option_text_field_controller"
application.register("select-option-text-field", SelectOptionTextFieldController)

import DownloadDocumentsController from "./download_documents_controller"
application.register("download_documents", DownloadDocumentsController)

import DateValidationController from "./date_validation_controller"
application.register("date_validation", DateValidationController)

import DfeAnalyticsEngagementTrackingController from "./dfe_analytics_engagement_tracking_controller"
application.register("dfe_analytics_engagement_tracking", DfeAnalyticsEngagementTrackingController);

import DfeAnalyticsLinksController from "./dfe_analytics_links_controller"
application.register("dfe_analytics_links", DfeAnalyticsLinksController);

import EngagementTrackingController from "./engagement_tracking_controller"
application.register("engagement-tracking", EngagementTrackingController);

import ExternalLinkTrackingController from "./external_link_tracking_controller"
application.register("external-link-tracking", ExternalLinkTrackingController);

import SearchToggleController from "./search_toggle_controller"
application.register("search-toggle", SearchToggleController);
