#!/bin/bash

echo -e "\n\n****************************************"
echo "Warning! Entering Production environment"
echo -e "****************************************\n\n"

cmd='cd /srv/app && PATH=$PATH:/usr/local/bundle/bin:/usr/local/bin rails '
cmd+=$@

echo -e "Performing: $cmd\n\n"

cf target -s sct-production
cf ssh buy-for-your-school-prod -t -c "$cmd"

echo -e "\n\nReminder: you are still in sct-production space..."
