name: Build and push docker image
description: Build and push docker image

inputs:
  target:
    description: The docker stage to target
    required: true
  ghcr_username:
    description: The username of the GHCR docker repo
    required: true
  ghcr_password:
    description: The password of the GHCR docker repo
    required: true

outputs:
  docker_image:
    description: The docker image and tag that has been built and pushed
    value: ${{ steps.prep.outputs.tagged_image }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      name: Checkout Code

    - name: Login to GitHub Container Registry
      if: github.actor != 'dependabot[bot]'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr_username }}
        password: ${{ inputs.ghcr_password }}

    - name: Prepare
      id: prep
      shell: bash
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)

        if [ "${{ inputs.target }}" == "test" ]; then
          echo ::set-output name=tagged_image::ghcr.io/dfe-digital/buy-for-your-school:${TAG}-test
        else
          echo ::set-output name=tagged_image::ghcr.io/dfe-digital/buy-for-your-school:${TAG}
        fi

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        push: ${{ github.actor != 'dependabot[bot]' }}
        target: ${{ inputs.target }}
        tags: ${{ steps.prep.outputs.tagged_image }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
