#!/bin/bash
# make sure to log into CF first ./script/cf-login

if [[ $(cf apps | grep buy-for-your-school-clamav-rest) != "" ]]; then
  echo "Already created..."
  exit 0
fi

cf create-app buy-for-your-school-clamav-rest --app-type docker
cf push buy-for-your-school-clamav-rest --docker-image niilo/clamav-rest

