#!/bin/bash
# call: ./script/create-application prod
# make sure to log into CF first ./script/cf-login

app_name="buy-for-your-school-clamav-rest-$1"

if [[ $(cf apps | grep $app_name) != "" ]]; then
  echo "Already created..."
  exit 0
fi

cf create-app $app_name --app-type docker
cf push $app_name --docker-image niilo/clamav-rest
cf unmap-route $app_name london.cloudapps.digital --hostname $app_name
cf map-route $app_name apps.internal --hostname $app_name
