#!/bin/bash

# Destroy the QA environment

cf login -u $CF_USER -p $CF_PASSWORD -a https://api.london.cloud.service.gov.uk -s $TF_VAR_cloudfoundry_space

# Exit if app does not exist ( no QA app )
if [[ $(cf apps | grep $CF_APP_NAME) ]]; then :
else
  # There is no app to delete
  exit 0
fi

# First empty out the S3 bucket - to avoid BucketNotEmpty error
cf ssh $CF_APP_NAME -c 'cd /srv/app; export PATH=$PATH:/usr/local/bundle/bin:/usr/local/bin; echo "Aws::S3::Resource.new.bucket(ENV[\"BUCKET_NAME\"]).objects.batch_delete!" | rails console'

# initialise terraform
cd terraform/app
terraform init

# destroy infrastructure and workspace

terraform workspace select $TF_VAR_environment
terraform destroy -input=false -auto-approve
terraform workspace select default
terraform workspace delete -force $TF_VAR_environment
