#!/bin/bash

# Map the QA static route to the instance

# wait for app to become started
until cf app $CF_APP_NAME | grep "requested state:" | grep started
do
  echo "Waiting for app to start..."
  sleep 2
done

sleep 10

# Now we can safely map the routes

cf map-route $CF_APP_NAME london.cloudapps.digital --hostname $STATIC_ROUTE
