#!/bin/bash

# Seed the QA environment

cf login -u $CF_USER -p $CF_PASSWORD -a https://api.london.cloud.service.gov.uk -s $TF_VAR_cloudfoundry_space

# Wait for app to become started
until $(cf ssh $CF_APP_NAME -c 'echo "Is the server running?"')
do
  echo "Waiting for app to start..."
  sleep 2
done

# Run seeding tasks
cf ssh $CF_APP_NAME -c 'cd /srv/app; PATH=$PATH:/usr/local/bundle/bin:/usr/local/bin rails case_management:seed_shared_inbox_emails' # quicker
cf ssh $CF_APP_NAME -c 'cd /srv/app; PATH=$PATH:/usr/local/bundle/bin:/usr/local/bin rails case_management:seed' # slower
