name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - research

env:
  GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
  GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
  GHCR_REPO: 'ghcr.io/dfe-digital/buy-for-your-school'
  CF_USER: ${{ secrets.CF_USER }}
  CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  turnstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/turnstyle@v1
        name: Check workflow concurrency
        with:
          poll-interval-seconds: 20
          same-branch-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: turnstyle
    runs-on: ubuntu-latest
    outputs:
      tf_var_docker_image: ${{ steps.tf_var_docker_image.outputs.value }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set Docker tag environment variable
        run: echo "DOCKER_TAG=${GITHUB_RUN_ID}-${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Set Docker Image environment variable
        run: echo "DOCKER_IMAGE=$GHCR_REPO:$DOCKER_TAG" >> $GITHUB_ENV
      - name: Set TFVAR Docker Image environment variable
        run: echo "TF_VAR_docker_image=$DOCKER_IMAGE" >> $GITHUB_ENV
      - name: Set TFVAR Docker Image output
        id: tf_var_docker_image
        run: echo "::set-output name=value::$TF_VAR_docker_image"
      - name: Build
        run: script/docker-push-ghcr
      - name: Notify
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          fields: workflow,job,commit,repo,ref,author,took
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # Deploy staging automatically on push to main
  deploy_staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    if: success() && github.ref == 'refs/heads/main' && github.event_name == 'push'
    env:
      TF_VAR_docker_image: ${{needs.build.outputs.tf_var_docker_image}}
      TF_VAR_cloudfoundry_space: "sct-staging"
      TF_VAR_environment: 'staging'
      GITHUB_SECRETS_JSON: ${{ toJson(secrets) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Terraform pin version
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.14.7

      - name: Cloudfoundry login
        run: |
          script/install-cf
          script/cf-login

      - name: Notify start deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.1
        id: rollbar_pre_deploy
        with:
          environment: staging-gpaas
          version: ${{ github.sha }}
          status: 'started'
          local_username: ${{ github.actor }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}

      - name: Deploy
        run: script/deploy-terraform

      - name: Link to clamav-rest
        run: script/clamav-rest/create-network-policy pre-prod buy-for-your-school-staging sct-staging

      - name: Notify finish deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.1
        id: rollbar_post_deploy
        with:
          environment: staging-gpaas
          version: ${{ github.sha }}
          status: ${{ job.status == 'success' && 'succeeded' || 'failed' }}
          local_username: ${{ github.actor }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          DEPLOY_ID: ${{ steps.rollbar_pre_deploy.outputs.deploy_id }}

  # Deploy research automatically on push to research
  deploy_research:
    needs: build
    runs-on: ubuntu-latest
    environment: research
    if: success() && github.ref == 'refs/heads/research'
    env:
      TF_VAR_docker_image: ${{needs.build.outputs.tf_var_docker_image}}
      TF_VAR_cloudfoundry_space: "sct-research"
      GITHUB_SECRETS_JSON: ${{ toJson(secrets) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Terraform pin version
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.14.7
      - name: Deploy terraform to research
        env:
          TF_VAR_environment: 'research'
        run: script/deploy-terraform

  # Deploy production manually on workflow dispatch
  deploy_production:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    if: success() && github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    env:
      TF_VAR_docker_image: ${{needs.build.outputs.tf_var_docker_image}}
      TF_VAR_cloudfoundry_space: "sct-production"
      TF_VAR_environment: 'prod'
      GITHUB_SECRETS_JSON: ${{ toJson(secrets) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Terraform pin version
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.14.7

      - name: Cloudfoundry login
        run: |
          script/install-cf
          script/cf-login

      - name: Notify start deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.1
        id: rollbar_pre_deploy
        with:
          environment: production-gpaas
          version: ${{ github.sha }}
          status: 'started'
          local_username: ${{ github.actor }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}

      - name: Deploy
        run: script/deploy-terraform

      - name: Map route
        run: cf map-route buy-for-your-school-prod get-help-buying-for-schools.service.gov.uk --hostname www

      - name: Connect to clamav-rest
        run: script/clamav-rest/create-network-policy prod buy-for-your-school-prod sct-production

      - name: Notify finish deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.1
        id: rollbar_post_deploy
        with:
          environment: production-gpaas
          version: ${{ github.sha }}
          status: ${{ job.status == 'success' && 'succeeded' || 'failed' }}
          local_username: ${{ github.actor }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          DEPLOY_ID: ${{ steps.rollbar_pre_deploy.outputs.deploy_id }}
