name: Build and push docker image
description: Build and push docker image

inputs:
  target:
    description: The docker stage to target
    required: true
  ghcr_username:
    description: The username of the GHCR docker repo
    required: true
  ghcr_password:
    description: The password of the GHCR docker repo
    required: true

outputs:
  docker_image:
    description: The docker image and tag that has been built and pushed
    value: ${{ steps.prep.outputs.main_tag }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      name: Checkout Code

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr_username }}
        password: ${{ inputs.ghcr_password }}

    - name: Prepare
      id: prep
      shell: bash
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        BASE_IMAGE=ghcr.io/dfe-digital/buy-for-your-school

        if [ "${{ inputs.target }}" == "test" ]; then
          echo main_tag=${BASE_IMAGE}:${TAG}-test >> $GITHUB_OUTPUT
          echo tags_to_push=${BASE_IMAGE}:${TAG}-test,${BASE_IMAGE}:latest-test >> $GITHUB_OUTPUT

        elif [ "${{ github.ref }}" == 'refs/heads/main' ]; then
          echo main_tag=${BASE_IMAGE}:${TAG} >> $GITHUB_OUTPUT
          echo tags_to_push=${BASE_IMAGE}:${TAG},${BASE_IMAGE}:main >> $GITHUB_OUTPUT

        elif [ "${{ github.ref }}" == 'refs/heads/development' ]; then
          echo main_tag=${BASE_IMAGE}:${TAG} >> $GITHUB_OUTPUT
          echo tags_to_push=${BASE_IMAGE}:${TAG},${BASE_IMAGE}:development >> $GITHUB_OUTPUT

        elif [ "${{ github.ref }}" == 'refs/heads/production' ]; then
          echo main_tag=${BASE_IMAGE}:${TAG} >> $GITHUB_OUTPUT
          echo tags_to_push=${BASE_IMAGE}:${TAG},${BASE_IMAGE}:production >> $GITHUB_OUTPUT

        else
          echo main_tag=${BASE_IMAGE}:${TAG} >> $GITHUB_OUTPUT
          echo tags_to_push=${BASE_IMAGE}:${TAG} >> $GITHUB_OUTPUT
        fi

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: v0.22.0

    - name: Build docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        push: ${{ github.actor != 'dependabot[bot]' }}
        target: ${{ inputs.target }}
        tags: ${{ steps.prep.outputs.tags_to_push }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
