warm_contentful_entry_cache:
  cron: "0 3 * * *"
  class: "WarmEntryCacheJob"
  description: This is a content driven service and the content is sourced by
    the Contentful API. As a single point of failure we have a Redis cache to
    provide some resilience to downtime or minor connection issues. As this
    service is used infrequently by real users, we automatically update the
    cache.

flag_stale_journeys:
  cron: "0 2 * * *"
  class: "FlagStaleJourneysJob"
  description: Change the state of a Journey to stale when it has not had any
    steps completed and has not been edited for a number of days. A stale Journey
    is one believed to be abandoned and cluttering the database.

delete_stale_journeys:
  cron: "0 2 * * *"
  class: "DeleteStaleJourneysJob"
  description: Automatically delete a stale Journey and associated child records
    after 30 days. This grace period gives a user the opportunity to prevent the
    deletion.

