warm_contentful_entry_cache:
  cron: 0 3 * * *
  class: WarmEntryCacheJob
  description: This is a content driven service and the content is sourced by
    the Contentful API. As a single point of failure we have a Redis cache to
    provide some resilience to downtime or minor connection issues. As this
    service is used infrequently by real users, we automatically update the
    cache.


# Supported ---------------

# TODO: adjust job to run immediately after new data is published
# first of the month @ 02:00
refresh_schools:
  cron: 0 2 1 * *
  class: Support::RefreshSchoolsJob
  description: Update internal school records using public data from GIAS. This
    is an expensive operation (10% @ 41k records persisted).

synchronize_shared_inbox:
  cron: "* * * * *" # every minute
  class: Support::SynchronizeSharedInboxJob
  description: Persist emails from the shared inbox into the database

resync_email_ids:
  cron: "* * * * *" # every minute
  class: Support::ResyncEmailIdsJob
  description: Get new outlook ids for emails moved between folders

refresh_establishment_groups:
  cron: 0 4 1 * * # At 04:00 on day-of-month 1.
  class: Support::RefreshEstablishmentGroupsJob
  description: Update internal EstablishmentGroup records using public data from GIAS.

sync_frameworks:
  cron: "0 0,12 * * *" # every midnight and midday
  class: Support::SyncFrameworksJob
  description: Fetch and persist frameworks from FaF
