#!/bin/sh
#
# Build and tag Docker images for development and test environments
#

set -e

# ghbs:dev
docker-compose -f docker-compose.yml -f docker-compose.dev.yml build

# ghbs:test
docker-compose -f docker-compose.yml -f docker-compose.test.yml build
