#!/bin/sh
#
# Docker development environment Rails console
#

set -e
echo "NB: run script/build if the image ghbs:dev does not exist locally"
echo "-----------------------------------------------------------------"

docker-compose -f docker-compose.yml -f docker-compose.dev.yml --project-name ghbs run --rm app bundle exec rails console
