#!/bin/sh

# script/destroy-volume: Trash a corrupt development database volume

set -e

git update-index --chmod=+x ./script/destroy-volume
docker-compose down --remove-orphans
docker volume rm buy-for-your-school_db-data