#!/bin/bash
# see .github/workflows/cleanup-qa-environments.yml

cd terraform/app

# Create app_env yaml file from GITHUB_SECRETS_JSON
echo "---" > qa_app_env.yml
echo "$GITHUB_SECRETS_JSON" | jq -r --arg e "$(echo "qa" | awk '{ print toupper($0) }' )" 'with_entries(select(.key | startswith("APP_ENV_" + $e) ) ) | keys[] as $k | "\($k[("APP_ENV_" + $e + "_" | length):]): \(.[$k])"' >> qa_app_env.yml

# destroy infrastructure and workspace
terraform workspaces select $TF_VAR_environment
terraform destroy -var-file=qa_app_env.yml -input=false -auto-approve
terraform workspaces delete $TF_VAR_environment
