#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --detach

check_container_name_format_command='docker ps --filter "name=buy-for-your-school_app_1" --format "{{.ID}}"'

if [[ $(eval $check_container_name_format_command) ]]; then
  docker attach buy-for-your-school_app_1
else
  docker attach buy-for-your-school-app-1
fi