#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --detach
docker attach buy-for-your-school_app_1
