#!/bin/sh
#
# Docker test environment Rspec suite
#

set -e
echo "NB: run script/build if the image ghbs:test does not exist locally"
echo "-----------------------------------------------------------------"

COMMAND_INPUT=$1

if [ -n "$COMMAND_INPUT" ]; then
  docker-compose -f docker-compose.yml -f docker-compose.test.yml --project-name ghbs run --rm app bundle exec rspec "$COMMAND_INPUT"
else
  docker-compose -f docker-compose.yml -f docker-compose.test.yml --project-name ghbs run --rm app bundle exec rake
fi
