#!/bin/sh

# script/test: Run the test suite for the application. Optionally pass in a path
#              to an individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

if [ -n "$DEBUG" ]; then
  set -x
fi

echo "==> Updating..."
script/update

TEST_FILE=$1

if [ -n "$TEST_FILE" ]; then
  echo "==> Running the tests matching '$TEST_FILE'..."
  bundle exec rspec --pattern "$TEST_FILE"
else
  if [ -n "$AUTOMATICALLY_FIX_LINTING" ]; then
    echo "==> Linting Ruby in fix mode..."
    bundle exec standardrb --fix
  else
    echo "==> Linting Ruby..."
    bundle exec standardrb
  fi

  echo "==> Running the tests..."
  bundle exec rspec

  echo "==> Running Brakeman"
  bundle exec brakeman -o /dev/stdout
fi
