#!/bin/sh

# script/test: Run the test suite for the application. Optionally pass in a path
#              to an individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

if [ -n "$DEBUG" ]; then
  set -x
fi

echo "==> Updating..."
script/update

TEST_FILE=$1

if [ -n "$TEST_FILE" ]; then
  echo "==> Running the tests matching '$TEST_FILE'..."
  bundle exec rspec --pattern "$TEST_FILE"
else
  echo "==> Linting Ruby..."
  bundle exec rake rubocop

  echo "==> CC Test Reporter Before Build... APP_URL $APPLICATION_URL CC_TEST_ID $CC_TEST_REPORTER_ID GIT_BRANCH $GIT_BRANCH GIT_COMMIT_SHA $GIT_COMMIT_SHA"
  cc-test-reporter before-build

  echo "==> Running the tests..."
  bundle exec rspec

  echo "==> CC Test Reporter After Build... APP_URL $APPLICATION_URL CC_TEST_ID $CC_TEST_REPORTER_ID GIT_BRANCH $GIT_BRANCH GIT_COMMIT_SHA $GIT_COMMIT_SHA"
  cc-test-reporter after-build --debug -t simplecov

  echo "==> Running Brakeman"
  bundle exec brakeman -o /dev/stdout
fi
