#!/bin/sh

# script/test: Run the test suite for the application. Optionally pass in a path
#              to an individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

if [ -n "$DEBUG" ]; then
  set -x
fi

DATE=$(date +'%s')
echo "==> Current date is '$DATE'"

echo "==> Updating..."
script/update

TEST_FILE=$1

if [ -n "$TEST_FILE" ]; then
  echo "==> Running the tests matching '$TEST_FILE'..."
  bundle exec rspec --pattern "$TEST_FILE"
else
  echo "==> Linting Ruby..."
  bundle exec rake rubocop

  echo "==> Running Brakeman"
  bundle exec brakeman -o /dev/stdout

  # Allow the command to pass every time, the below will return non-0 exit code
  # if there are failures after second attempt
  echo "==> Running the tests..."
  RSPEC_EXIT_CODE=0
  bundle exec rspec || (RSPEC_EXIT_CODE=1)
  # Re run once if there are any failures
  bundle exec rspec --only-failures || (RSPEC_EXIT_CODE=1)

  exit $RSPEC_EXIT_CODE
fi
