# Grouped categories of spend supported by Get Help buying for Schools service
#
#
#
---

towers:
  - title: ICT
  - title: Energy & Utilities
  - title: FM & Catering
  - title: Services

categories:
  - title: ICT
    description: Information and Communications Technology
    slug: ict
    tower: ICT
    sub_categories:
      - title: AV Displays
        description: TVs, projectors
        slug: displays
      - title: Broadband Infrastructure
        slug: broadband_infrastructure
        is_archived: true
      - title: Broadband service
        slug: broadband_service
        is_archived: true
      - title: Cloud SaaS
        slug: cloud_saas
      - title: Curriculum Content
        slug: curriculum_content
      - title: Cyber services
        slug: cyber_services
      - title: Funding - non procurement requests
      - title: Hosting & Storage
        slug: hosting_and_storage
      - title: Laptops
        description: Mobile computing
        slug: laptops
      - title: MFD
        slug: mfd
      - title: MIS
        slug: mis
      - title: OS Software
        slug: software
      - title: Peripherals
        description: computer peripherals
        slug: peripherals
      - title: Platforms (VLEs)
        description: Platforms - Virtual Learning Environments
        slug: vle
      - title: Safeguarding & Content
        slug: safeguarding
      - title: Server Configuration & Support
        slug: servers
      - title: Switches & Routers
        description: networking hardware
        slug: switches_routers
      - title: Telecoms & Broadband
        slug: broadband
      - title: Websites
        slug: websites
      - title: Other (ICT)

  - title: FM
    description: Facilities Management
    slug: facilities
    tower: FM & Catering
    sub_categories:
      - title: Boilers and plumbing services
      - title: Building maintenance & BMS
      - title: Cleaning Products
      - title: Cleaning Services
      - title: Construction
      - title: Fire Safety (Goods & Systems)
      - title: Furniture
      - title: Grounds & Winter Maintenance
      - title: IPC (PPE & Uniform)
        is_archived: true
      - title: Mechanical & Electrical Systems
      - title: Modular Buildings
      - title: MUGAs
      - title: PPE
      - title: Removal & relocation
      - title: Roof Maintenance
      - title: Security & CCTV
      - title: Statutory testing & FM Compliance
      - title: Uniform
      - title: Waste management
      - title: Water, drains & sewerage
        slug: sewerage
      - title: Vending Machine
      - title: Other (FM)

  - title: Energy
    slug: energy
    tower: Energy & Utilities
    sub_categories:
      - title: Decarbonisation
      - title: Electricity
      - title: Gas
      - title: Other fuels
      - title: Solar
      - title: Other (Energy)

  - title: Utilities
    slug: utilities
    tower: Energy & Utilities
    sub_categories:
      - title: Water
      - title: Other (Utilities)

  - title: Catering
    slug: catering
    tower: FM & Catering
    sub_categories:
      - title: Breakfast Club
      - title: Catering Equipment
      - title: Catering Services
      - title: Other (Catering)

  - title: Furniture
    slug: furniture
    tower: FM & Catering
    is_archived: true
    sub_categories: []

  - title: Books
    slug: books
    tower: Services
    is_archived: true
    sub_categories: []

  - title: Business Services
    slug: business
    tower: Services
    sub_categories:
      - title: Audit Accessibility (buildings and digital)
      - title: Audit Financial
      - title: Audit Safegarding
      - title: Books
      - title: Insurance
      - title: Leasing
      - title: Property leasing agents
      - title: Spend Analysis
      - title: Stationery supply & office supplies
      - title: Transport
      - title: Other (BS)

  - title: Financial
    slug: financial
    tower: Services
    is_archived: true
    sub_categories:
      - title: Audit
        is_archived: true

  - title: Professional Services
    slug: professional-services
    tower: Services
    sub_categories:
      - title: Consultancy
      - title: HR
      - title: Legal Services
      - title: Payroll
      - title: Recruitment of other staff
      - title: Recruitment screening
      - title: Specialist professional services
      - title: Supply Teachers & Agency workers
      - title: Other (PS)

  - title: Office supplies
    slug: office_supplies
    tower: Services
    is_archived: true
    sub_categories: []

  - title: Capital
    slug: capital
    is_archived: true
    sub_categories: []

  - title: Or
    slug: or
    sub_categories:
      - title: Not yet known
      - title: Other (General)
