name: "CI/CD - Deploy Production"

on:
  workflow_dispatch:
    inputs:
      docker_image_and_tag:
        description: The docker image and tag you wish to deploy. e.g. ghcr.io/dfe-digital/buy-for-your-school:XYZ
        required: true

jobs:
  release_production:
    name: Deploy release (Production)
    runs-on: ubuntu-20.04
    environment: production

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0

      - uses: ./.github/workflows/actions/deploy
        name: Deploy
        id: deploy
        with:
          docker_image: ${{ inputs.docker_image_and_tag }}
          deployment_environment: production
          pr_number: ${{ github.event.number }}
          github_secrets_json: ${{ toJson(secrets) }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          rollbar_access_token: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

