name: Contentful clone - Master to Staging
on:
  workflow_dispatch:
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g contentful-cli

      - name: Authenticate with Contentful
        run: contentful login --management-token ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}

      - name: Delete previous staging environment
        run: contentful space --space-id ${{ secrets.APP_ENV_PROD_CONTENTFUL_SPACE }} environment delete --environment-id staging

      - name: Clone master environment to a new staging environment
        run: contentful space --space-id ${{ secrets.APP_ENV_PROD_CONTENTFUL_SPACE }} environment create --name staging --environment-id staging --source master

      - name: Cache bust the staging category record to refresh the environment
        run: |
          curl -XPOST -H 'Authorization: Token ${{ secrets.CONTENTFUL_WEBHOOK_API_KEY }}' -H "Content-type: application/json" -d '{
            "entityId": "${{ secrets.APP_ENV_PROD_CONTENTFUL_DEFAULT_CATEGORY_ENTRY }}",
            "spaceId": "${{ secrets.APP_ENV_PROD_CONTENTFUL_SPACE }}"
          }' '${{ secrets.STAGING_URL }}/api/contentful/entry_updated'
