name: "Support - Update SSL Cert Validation"

on:
  workflow_dispatch:
  schedule:
    # At 09:00 on Monday. https://crontab.guru/#0_9_*_*_MON
    - cron: '0 9 * * MON'

jobs:
  check_need_to_validate_and_potentially_update:
    strategy:
      fail-fast: false
      matrix:
        environment: [az-dev, az-staging, az-production]

    # we must use a shared workflow in order to have 2 environments for prod (read only and normal)
    # this is so we can check the status of the validation without needing deployment approval.
    # Also so we can use matrix strategy with sequential jobs and keep outputs intact.
    uses: ./.github/workflows/support-update-ssl-cert-validation-implementation.yml

    with:
      chosen_environment: ${{ matrix.environment }}

    secrets: inherit
